name: cicd_lecture_2

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  testing-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install .
      - name: Test check
        run: pytest
